name: Compile

on: [push]

jobs:
  build-ubuntu:
      runs-on: ubuntu-latest
      container: ubuntu:rolling
      steps:
      - uses: actions/checkout@v1
      - name: install-packages
        run:  apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install build-essential git pkg-config zlib1g-dev cmake clang libclang-dev libcrypto++-dev lld
      - name: cmake
        run: cmake -S . -B out
      - name: compile
        run: cmake --build out --parallel 8
      - name: test
        run: cmake --build out --target fixpoint-check
  sanitize:
      runs-on: ubuntu-latest
      container: ubuntu:rolling
      steps:
      - uses: actions/checkout@v1
      - name: install-packages
        run:  apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install build-essential git pkg-config zlib1g-dev cmake clang libclang-dev libcrypto++-dev lld
      - name: cmake
        run: cmake -S . -B out-sanitize -DCMAKE_BUILD_TYPE=DebugASan
      - name: compile
        run: cmake --build out-sanitize --parallel 8
      - name: test
        run: cmake --build out-sanitize --target fixpoint-check
