name: Compile

on: [push]

jobs:
  build-ubuntu:
      runs-on: ubuntu-latest
      container: ghcr.io/fixpointos/wasm_toolchain_docker:latest
      steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: 'echo HOME=/home | sudo tee -a $GITHUB_ENV'
      - name: cmake
        run: cmake -S . -B out
      - name: compile
        run: cmake --build out --parallel 8
      - name: test
        run: cmake --build out --target fixpoint-check
  sanitize:
      runs-on: ubuntu-latest
      container: ghcr.io/fixpointos/wasm_toolchain_docker:latest
      steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: 'echo HOME=/home | sudo tee -a $GITHUB_ENV'
      - name: cmake
        run: cmake -S . -B out-sanitize -DCMAKE_BUILD_TYPE=DebugASan
      - name: compile
        run: cmake --build out-sanitize --parallel 8
      - name: test
        run: cmake --build out-sanitize --target fixpoint-check
